
/* Automatically generated by make_options_def.py. */

#ifndef OPTIONS_DEFS_H
#define OPTIONS_DEFS_H

const char* option_defs[] = {
    "__AUTO_SETEUID__", "",
    "__CFG_COMPILER_STACK_SIZE__", "600",
    "__CFG_EVALUATOR_STACK_SIZE__", "65536",
    "__CFG_LIVING_HASH_SIZE__", "256",
    "__CFG_MAX_CALL_DEPTH__", "150",
    "__CFG_MAX_GLOBAL_VARIABLES__", "65536",
    "__CFG_MAX_LOCAL_VARIABLES__", "50",
    "__COMMAND_BUF_SIZE__", "2000",
    "__CUSTOM_CRYPT__", "",
    "__DEFAULT_PRAGMAS__", "PRAGMA_WARNINGS + PRAGMA_SAVE_TYPES + PRAGMA_ERROR_CONTEXT + PRAGMA_OPTIMIZE",
    "__ED_INDENT_SPACES__", "4",
    "__ED_TAB_WIDTH__", "8",
    "__LARGEST_PRINTABLE_STRING__", "8192",
    "__LARGE_STRING_SIZE__", "1000",
    "__MAX_SAVE_SVALUE_DEPTH__", "100",
    "__OLD_ED__", "",
    "__PACKAGE_CONTRIB__", "",
    "__PACKAGE_CORE__", "",
    "__PACKAGE_DEVELOP__", "",
    "__PACKAGE_MATH__", "",
    "__PACKAGE_MUDLIB_STATS__", "",
    "__PACKAGE_OPS__", "",
    "__PACKAGE_TRIM__", "",
    "__PACKAGE_UIDS__", "",
    "__REF_RESERVED_WORD__", "",
    "__RESTRICTED_ED__", "",
    "__SAVE_EXTENSION__", "\".o\"",
    "__SAVE_GZ_EXTENSION__", "\".o.gz\"",
    "__SMALL_STRING_SIZE__", "100",
    "__STRUCT_CLASS__", "",
    "__STRUCT_STRUCT__", "",
    "__USE_32BIT_ADDRESSES__", "",

};

#endif
